dist: trusty
sudo: false
language: php

php:
  - 7.3
  - 7.4

env:
  - CODECOV_TOKEN="e2bfdde9-5657-472b-bab2-8e2342933ba0"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - travis_retry composer update --prefer-dist

jobs:
  include:
    - stage: Test
      if: type = cron
      php: 7.4

    - stage: Test
      if: type = cron
      php: 7.3
      install:
        - composer config minimum-stability dev
        - travis_retry composer update --prefer-dist

    - stage: Test
      env: CODECOV_TOKEN="e2bfdde9-5657-472b-bab2-8e2342933ba0"
      before_script:
          - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
          - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        ./vendor/bin/phpunit

    - stage: Code Quality
      install: travis_retry composer install --prefer-dist
      before_script:
        - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      script: vendor/bin/phpstan analyse

    - stage: Code Quality
      install: travis_retry composer install --prefer-dist
      php: 7.3
      script:
        - ./vendor/bin/phpcs --ignore="*/Tests/*"

    #- stage: Code Quality
    #  install: travis_retry composer install --prefer-dist
    #  before_script:
    #    - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar
    #    - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar.asc
    #    - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
    #    - gpg --with-fingerprint --verify infection.phar.asc infection.phar
    #    - chmod +x infection.phar
    #    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
    #    - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
    #  php: 7.3
    #  script:
    #    - ./infection.phar --min-msi=48 --threads=4

  #allow_failures:
  #  - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache
