dist: trusty
sudo: false
language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  - CODECOV_TOKEN="e2bfdde9-5657-472b-bab2-8e2342933ba0"

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - sh -e ./.travis-compile.sh
  - composer self-update

install:
  - travis_retry composer update --prefer-dist

jobs:
  include:
    - stage: Test
      if: type = cron
      php: 7.2

    - stage: Test
      if: type = cron
      php: 7.4snapshot

    - stage: Test
      if: type = cron
      php: 7.3
      install:
        - composer config minimum-stability dev
        - travis_retry composer update --prefer-dist

    - stage: Test
      env: CODECOV_TOKEN="e2bfdde9-5657-472b-bab2-8e2342933ba0"
      before_script:
          - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
          - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        ./vendor/bin/phpunit

    - stage: Code Quality
      install: travis_retry composer install --prefer-dist
      before_script:
        - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      script: vendor/bin/phpstan analyse

    - stage: Code Quality
      install: travis_retry composer install --prefer-dist
      php: 7.2
      script:
        - ./vendor/bin/phpcs

  allow_failures:
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack:
    appsdocks:CHHxTYhIPcoKrd3pxxgvFKEv
    on_success: never
    on_failure: always