language: php

php:
  - 7.3
  - 7.4

env:
  - CODECOV_TOKEN="e2bfdde9-5657-472b-bab2-8e2342933ba0"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - travis_retry composer update --prefer-dist --no-suggest --no-progress --no-interaction

jobs:
  include:
    - stage: Test
      if: type = cron
      php: 7.4

    - stage: Test
      if: type = cron
      php: 7.3
      install:
        - composer config minimum-stability dev
        - travis_retry composer update --prefer-dist

    - stage: Test
      env: CODECOV_TOKEN="e2bfdde9-5657-472b-bab2-8e2342933ba0"
      before_script:
          - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
          - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - composer run-script test

    - stage: Static Code Analysis
      php: 7.4
      install: travis_retry composer install --prefer-dist
      before_script:
        - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      script:
        - composer run-script phpstan

    - stage: Coding Standard
      install: travis_retry composer install --prefer-dist
      php: 7.3
      script:
        - composer run-script phpcs

    - stage: Test Quality
      install: travis_retry composer install --prefer-dist
      before_script:
        - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar
        - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar.asc
        - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
        - gpg --with-fingerprint --verify infection.phar.asc infection.phar
        - chmod +x infection.phar
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      php: 7.3
      script:
        - composer run-script infection

  allow_failures:
    - stage: Test Quality
    - stage: Coding Standard
    - stage: Static Code Analysis

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
